package com.kafka.exam.kafkaexam.outbox

enum class OutboxEventType {
    PRODUCT_REGISTERED,
    PRODUCT_UPDATED,
    PRODUCT_DELETED,

    // Saga Commands
    CREATE_ORDER,
    CANCEL_ORDER,
    PROCESS_PAYMENT,
    CANCEL_PAYMENT,
    RESERVE_INVENTORY,
    RELEASE_INVENTORY,

    // Saga Events
    ORDER_CREATED,
    ORDER_CANCELLED,
    PAYMENT_COMPLETED,
    PAYMENT_FAILED,
    PAYMENT_CANCELLED,
    INVENTORY_RESERVED,
    INVENTORY_FAILED,
    INVENTORY_RELEASED
}